export const UPDATE_FOCUSED_TRUE = 'header/UPDATE_FOCUSED_TRUE';
export const UPDATE_FOCUSED_FALSE = 'Header/UPDATE_FOCUSED_FALSE';
export const CHANGE_SEARCH_LIST = 'Header/CHANGE_SEARCH_LIST';
export const CHANGE_MOUSE_ENTER = 'Header/CHANGE_MOUSE_ENTER';
export const CHANGE_MOUSE_LEAVE = 'Header/CHANGE_MOUSE_LEAVE';
export const UPDATE_CHANGE_PAGE = 'Header/UPDATE_CHANGE_PAGE';